
sudo: required
language: java

jdk:
    - openjdk7

script:
  - mvn package

before_deploy:
    - tar -zcvf result.tar.gz /home/travis/build/rafaelmotaalves/jsoup/target

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
            